#!/bin/bash
echo '=== VERCEL IMAGE DIAGNOSTIC SCRIPT ==='
echo ''
echo 'Run these curl commands on Vercel to see what is actually being served:'
echo ''
echo '1. Check if image is HTML (BROKEN):'
echo '   curl -s http://your-vercel-url.vercel.app/images/schbuilding.jpeg | head -5'
echo '   If you see <!DOCTYPE html> or <html>, it is broken.'
echo ''
echo '2. Check if image is actual JPEG (WORKING):'
echo '   curl -sI http://your-vercel-url.vercel.app/images/schbuilding.jpeg | grep Content-Type'
echo '   Should show: Content-Type: image/jpeg'
echo ''
echo '3. Download and check file type:'
echo '   curl -s http://your-vercel-url.vercel.app/images/schbuilding.jpeg -o /tmp/test.jpg'
echo '   file /tmp/test.jpg'
echo '   Should show: JPEG image data'
echo ''
